In [1]:
import numpy as np
import pandas as pd

In [2]:
#Set viewing options
pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False)

In [3]:
qwins = pd.read_csv('data/QuarterlyWins.csv')

In [4]:
qwins.head()

   Unnamed: 0  X        GameID  Week  Day   DateStamp     Vteam  VQ1  VQ2  VQ3  VQ4  Year     Hteam  HQ1  HQ2  HQ3  HQ4      Date    Time RQ1 RQ2 RQ3 RQ4  Win Winner
0           1  0  200009030min     1  Sun  2000-09-03     Bears    7    6    7    7  2000   Vikings    6    3    7   14  9/3/2000  1:00PM   V   V   T   H   -3     HW
1           2  1  200009030kan     1  Sun  2000-09-03     Colts    0    7    7   13  2000    Chiefs    0    7    7    0  9/3/2000  1:00PM   T   T   T  VV   13     VW
2           3  2  200009030was     1  Sun  2000-09-03  Panthers   10    0    0    7  2000  Redskins    7    0    3   10  9/3/2000  1:01PM   V   T   H   H   -3     HW
3           4  3  200009030atl     1  Sun  2000-09-03     49ers    7    7    7    7  2000   Falcons    6   16   14    0  9/3/2000  1:02PM   V  HH   H   V   -8     HW
4           5  4  200009030pit     1  Sun  2000-09-03    Ravens   10    3    3    0  2000  Steelers    0    0    0    0  9/3/2000  1:02PM  VV   V   V   T   16     VW

In [5]:
#null (baseline) model
qwins['Winner'].value_counts()

HW    2855
VW    2136
T      333
Name: Winner, dtype: int64

In [6]:
#null (baseline) model
qwins['Winner'].value_counts(normalize=True)

HW    0.536251
VW    0.401202
T     0.062547
Name: Winner, dtype: float64

In [7]:
qwins.iloc[4235:4265,:]

      Unnamed: 0     X                      GameID  Week  Day   DateStamp       Vteam  VQ1  VQ2  VQ3  VQ4  Year      Hteam  HQ1  HQ2  HQ3  HQ4       Date    Time RQ1  RQ2 RQ3 RQ4  Win Winner
4235        4236  4235      2015-17-SteelersBrowns    17  Sun  2016-01-03    Steelers    7    7    3   11  2015     Browns    3    6    0    3   1/3/2016  1:02PM   V    V   V  VV   16     VW
4236        4237  4236           2015-17-JetsBills    17  Sun  2016-01-03        Jets    0    7   10    0  2015      Bills    7    9    3    3   1/3/2016  1:02PM   H    H   V   H   -5     HW
4237        4238  4237          2015-17-LionsBears    17  Sun  2016-01-03       Lions    7    3    7    7  2015      Bears    0    0   10   10   1/3/2016  1:03PM   V    V   H   H    4     VW
4238        4239  4238       2015-17-RavensBengals    17  Sun  2016-01-03      Ravens    0    9    0    7  2015    Bengals    0    7   14    3   1/3/2016  1:03PM   T    V  HH   V   -8     HW
4239        4240  4239           2015-17-Rams49ers    17  Sun  2016-01-03        Rams    3   13    0    0  2015      49ers    0   10    3    3   1/3/2016  4:25PM   V    V   H   H    0      T
4240        4241  4240     2015-17-ChargersBroncos    17  Sun  2016-01-03    Chargers    3    3    7    7  2015    Broncos    7    0    7   13   1/3/2016  4:25PM   H    V   T   H   -7     HW
4241        4242  4241  2015-17-BuccaneersPanthers    17  Sun  2016-01-03  Buccaneers    3    0    7    0  2015   Panthers    0   24    7    7   1/3/2016  4:25PM   V  HHH   T   H  -28     HW
4242        4243  4242   2015-17-SeahawksCardinals    17  Sun  2016-01-03    Seahawks   10   20    6    0  2015  Cardinals    0    6    0    0   1/3/2016  4:25PM  VV   VV   V   T   30     VW
4243        4244  4243       2015-17-RaidersChiefs    17  Sun  2016-01-03     Raiders    0   10    0    7  2015     Chiefs   14    0    9    0   1/3/2016  4:26PM  HH   VV  HH   V   -6     HW
4244        4245  4244      2015-17-VikingsPackers    17  Sun  2016-01-03     Vikings    3    3   14    0  2015    Packers    3    0    0   10   1/3/2016  8:30PM   T    V  VV  HH    7     VW
4245        4246  4245     2016-1-SteelersRedskins   100  Sat  2016-01-09    Steelers    0   14   10   14  2016   Redskins    6    0    3    7   1/9/2016  4:35PM   H   VV   V   V   22     VW
4246        4247  4246            2016-1-Rams49ers   100  Sat  2016-01-09        Rams    0    0    0    0  2016      49ers    7    7    0   14   1/9/2016  8:15PM   H    H   T  HH  -28     HW
4247        4248  4247    2016-1-BuccaneersFalcons   100  Sun  2016-01-10  Buccaneers    3   14   14    0  2016    Falcons   10    3    8    3  1/10/2016  1:05PM   H   VV   V   H    7     VW
4248        4249  4248         2016-1-BrownsEagles   100  Sun  2016-01-10      Browns    0    7    3    0  2016     Eagles    7    6    9    7  1/10/2016  4:42PM   H    V   H   H  -19     HW
4249        4250  4249        2016-1-VikingsTitans   200  Sat  2016-01-16     Vikings    0    0   12   13  2016     Titans    3    7    0    6  1/16/2016  4:35PM   H    H  VV   V    9     VW
4250        4251  4250        2016-1-RaidersSaints   200  Sat  2016-01-16     Raiders   10    0    3   22  2016     Saints    3   14    7   10  1/16/2016  8:15PM   V   HH   H  VV    1     VW
4251        4252  4251          2016-1-BengalsJets   200  Sun  2016-01-17     Bengals    3   10    7    3  2016       Jets    7    9    0    6  1/17/2016  1:06PM   H    V   V   H    1     VW
4252        4253  4252       2016-1-ChargersChiefs   200  Sun  2016-01-17    Chargers    7   14    3    3  2016     Chiefs    3    0    7   17  1/17/2016  4:40PM   V   VV   H  HH    0      T
4253        4254  4253          2016-1-BearsTexans   300  Sun  2016-01-24       Bears    7    7    0    0  2016     Texans    0   10    3   10  1/24/2016  3:05PM   V    H   H  HH   -9     HW
4254        4255  4254          2016-1-BillsRavens   300  Sun  2016-01-24       Bills    0    7    0    0  2016     Ravens    3    7    0    3  1/24/2016  6:42PM   H    T   T   H   -6     HW
4255        4256  4255       2016-1-PackersJaguars   400  Sun  2016-02-07     Packers    7   14    3    3  2016    Jaguars    7   10    3    3   2/7/2016  6:39PM   T    V   T   T    4     VW
4256        4257  4256     2016-1-DolphinsSeahawks     1  Thu  2016-09-08    Dolphins    0    3    0    7  2016   Seahawks    3    3    0    6   9/8/2016  8:40PM   H    T   T   V   -2     HW
4257        4258  4257           2016-1-LionsColts     1  Sun  2016-09-11       Lions    7   14    7   11  2016      Colts    0   10    8   17  9/11/2016  1:04PM   V    V   H   H    4     VW
4258        4259  4258        2016-1-GiantsCowboys     1  Sun  2016-09-11      Giants    0   13    0    7  2016    Cowboys    3    6    7    3  9/11/2016  1:04PM   H    V   H   V    1     VW
4259        4260  4259    2016-1-PatriotsCardinals     1  Sun  2016-09-11    Patriots   10    0    7    6  2016  Cardinals    0    7    7    7  9/11/2016  1:05PM  VV    H   T   H    2     VW
4260        4261  4260      2016-1-PanthersBroncos     1  Sun  2016-09-11    Panthers    7   10    0    3  2016    Broncos    0    7    0   14  9/11/2016  1:05PM   V    V   T  HH   -1     HW
4261        4262  4261          2016-2-EaglesBears     1  Sun  2016-09-11      Eagles    3    6   13    7  2016      Bears    0    7    0    7  9/11/2016  1:05PM   V    H  VV   T   15     VW
4262        4263  4262         2016-2-SaintsGiants     1  Sun  2016-09-11      Saints    0    3    0   10  2016     Giants    0    7    3    6  9/11/2016  1:05PM   T    H   H   V   -3     HW
4263        4264  4263        2016-2-49ersPanthers     1  Sun  2016-09-11       49ers    3    7    0   17  2016   Panthers    7   10   14   15  9/11/2016  1:05PM   H    H  HH   V  -19     HW
4264        4265  4264      2016-2-CowboysRedskins     1  Sun  2016-09-11     Cowboys   10    3    7    7  2016   Redskins    0   10   13    0  9/11/2016  1:05PM  VV    H   H   V    4     VW

In [8]:
quarterly_wins = qwins[['RQ1','RQ2','RQ3','RQ4','Winner']]
quarterly_wins

     RQ1  RQ2 RQ3  RQ4 Winner
0      V    V   T    H     HW
1      T    T   T   VV     VW
2      V    T   H    H     HW
3      V   HH   H    V     HW
4     VV    V   V    T     VW
...   ..  ...  ..  ...    ...
5319   T    H  HH    H     HW
5320   V    V  VV    H     VW
5321   V    H   T    H     HW
5322   H  HHH   T   VV     HW
5323   H    V  VV  HHH     HW

[5324 rows x 5 columns]

In [9]:
quarterly_wins['Winner'].value_counts(normalize=True)
# About 1 out of every 16 NFL games goes to overtime

HW    0.536251
VW    0.401202
T     0.062547
Name: Winner, dtype: float64

In [10]:
quarterly_wins_no_target = quarterly_wins.drop(['Winner'], axis=1)

In [11]:
quarterly_wins_no_target

     RQ1  RQ2 RQ3  RQ4
0      V    V   T    H
1      T    T   T   VV
2      V    T   H    H
3      V   HH   H    V
4     VV    V   V    T
...   ..  ...  ..  ...
5319   T    H  HH    H
5320   V    V  VV    H
5321   V    H   T    H
5322   H  HHH   T   VV
5323   H    V  VV  HHH

[5324 rows x 4 columns]

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
ohe = OneHotEncoder()
quarterly_wins_encoded = pd.DataFrame(ohe.fit_transform(quarterly_wins_no_target).toarray())
ohe.get_feature_names()
quarterly_wins_encoded.columns = ohe.get_feature_names()
#pd.DataFrame(enc.fit_transform(bridge_df[['Bridge_Types_Cat']]).toarray())

In [14]:
quarterly_wins_encoded

      x0_H  x0_HH  x0_HHH  x0_T  x0_V  x0_VV  x0_VVV  x1_H  x1_HH  x1_HHH  x1_T  x1_V  x1_VV  x1_VVV  x2_H  x2_HH  x2_HHH  x2_T  x2_V  x2_VV  x2_VVV  x3_H  x3_HH  x3_HHH  x3_T  x3_V  x3_VV  x3_VVV
0      0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0
1      0.0    0.0     0.0   1.0   0.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   0.0    0.0     0.0   0.0   0.0    1.0     0.0
2      0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0
3      0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    1.0     0.0   0.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0
4      0.0    0.0     0.0   0.0   0.0    1.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0
...    ...    ...     ...   ...   ...    ...     ...   ...    ...     ...   ...   ...    ...     ...   ...    ...     ...   ...   ...    ...     ...   ...    ...     ...   ...   ...    ...     ...
5319   0.0    0.0     0.0   1.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    1.0     0.0   0.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0
5320   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   0.0    1.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0
5321   0.0    0.0     0.0   0.0   1.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0
5322   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    0.0     1.0   0.0   0.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   0.0    0.0     0.0   0.0   0.0    1.0     0.0
5323   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   0.0    1.0     0.0   0.0    0.0     1.0   0.0   0.0    0.0     0.0

[5324 rows x 28 columns]

In [15]:
quarterly_wins_for_modeling = pd.concat([quarterly_wins_encoded, quarterly_wins['Winner']],axis=1)
quarterly_wins_for_modeling

      x0_H  x0_HH  x0_HHH  x0_T  x0_V  x0_VV  x0_VVV  x1_H  x1_HH  x1_HHH  x1_T  x1_V  x1_VV  x1_VVV  x2_H  x2_HH  x2_HHH  x2_T  x2_V  x2_VV  x2_VVV  x3_H  x3_HH  x3_HHH  x3_T  x3_V  x3_VV  x3_VVV Winner
0      0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0     HW
1      0.0    0.0     0.0   1.0   0.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   0.0    0.0     0.0   0.0   0.0    1.0     0.0     VW
2      0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0     HW
3      0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    1.0     0.0   0.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0     HW
4      0.0    0.0     0.0   0.0   0.0    1.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0     VW
...    ...    ...     ...   ...   ...    ...     ...   ...    ...     ...   ...   ...    ...     ...   ...    ...     ...   ...   ...    ...     ...   ...    ...     ...   ...   ...    ...     ...    ...
5319   0.0    0.0     0.0   1.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    1.0     0.0   0.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0     HW
5320   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   0.0    1.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0     VW
5321   0.0    0.0     0.0   0.0   1.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0     HW
5322   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    0.0     1.0   0.0   0.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   0.0    0.0     0.0   0.0   0.0    1.0     0.0     HW
5323   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   0.0    1.0     0.0   0.0    0.0     1.0   0.0   0.0    0.0     0.0     HW

[5324 rows x 29 columns]

In [16]:
winner_codes = {"Winner":     {"HW": -1, "VW": 1, "T": 0}}
quarterly_wins_for_modeling = quarterly_wins_for_modeling.replace(winner_codes)
quarterly_wins_for_modeling

      x0_H  x0_HH  x0_HHH  x0_T  x0_V  x0_VV  x0_VVV  x1_H  x1_HH  x1_HHH  x1_T  x1_V  x1_VV  x1_VVV  x2_H  x2_HH  x2_HHH  x2_T  x2_V  x2_VV  x2_VVV  x3_H  x3_HH  x3_HHH  x3_T  x3_V  x3_VV  x3_VVV  Winner
0      0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0      -1
1      0.0    0.0     0.0   1.0   0.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   0.0    0.0     0.0   0.0   0.0    1.0     0.0       1
2      0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0      -1
3      0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    1.0     0.0   0.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0      -1
4      0.0    0.0     0.0   0.0   0.0    1.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0       1
...    ...    ...     ...   ...   ...    ...     ...   ...    ...     ...   ...   ...    ...     ...   ...    ...     ...   ...   ...    ...     ...   ...    ...     ...   ...   ...    ...     ...     ...
5319   0.0    0.0     0.0   1.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    1.0     0.0   0.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0      -1
5320   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   0.0    1.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0       1
5321   0.0    0.0     0.0   0.0   1.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   1.0    0.0     0.0   0.0   0.0    0.0     0.0      -1
5322   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    0.0     1.0   0.0   0.0    0.0     0.0   0.0    0.0     0.0   1.0   0.0    0.0     0.0   0.0    0.0     0.0   0.0   0.0    1.0     0.0      -1
5323   1.0    0.0     0.0   0.0   0.0    0.0     0.0   0.0    0.0     0.0   0.0   1.0    0.0     0.0   0.0    0.0     0.0   0.0   0.0    1.0     0.0   0.0    0.0     1.0   0.0   0.0    0.0     0.0      -1

[5324 rows x 29 columns]

In [ ]:
quarterly_wins_for_modeling.to_csv('data/Quarterly_Wins-for_Modeling.csv', index=False)