In [1]:
import numpy as np
import pandas as pd

In [2]:
#Set viewing options
pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False)

In [3]:
games = pd.read_csv('data/MasterGames_2000to2019.csv')

In [18]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5324 entries, 0 to 5323
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   5324 non-null   int64
 1   GameID       5324 non-null   object
 2   Week         5324 non-null   int64
 3   Day          5324 non-null   object
 4   DateStamp    5324 non-null   object
 5   Vteam        5324 non-null   object
 6   VQ1          5324 non-null   int64
 7   VQ2          5324 non-null   int64
 8   VQ3          5324 non-null   int64
 9   VQ4          5324 non-null   int64
 10  Year         5324 non-null   int64
 11  Hteam        5324 non-null   object
 12  HQ1          5324 non-null   int64
 13  HQ2          5324 non-null   int64
 14  HQ3          5324 non-null   int64
 15  HQ4          5324 non-null   int64
 16  Date         5324 non-null   object
 17  Time         5324 non-null   object
 18  Winner/tie   5324 non-null   object
 19  Unnamed: 18  2296 non-null   object
 20  Loser/tie    5324 non-null   object
dtypes: int64(11), object(10)
memory usage: 873.6+ KB

In [4]:
games.head()

   Unnamed: 0        GameID  Week  Day   DateStamp     Vteam  VQ1  VQ2  VQ3  VQ4  Year     Hteam  HQ1  HQ2  HQ3  HQ4      Date    Time           Winner/tie Unnamed: 18            Loser/tie
0           0  200009030min     1  Sun  2000-09-03     Bears    7    6    7    7  2000   Vikings    6    3    7   14  9/3/2000  1:00PM    Minnesota Vikings         NaN        Chicago Bears
1           1  200009030kan     1  Sun  2000-09-03     Colts    0    7    7   13  2000    Chiefs    0    7    7    0  9/3/2000  1:00PM   Indianapolis Colts           @   Kansas City Chiefs
2           2  200009030was     1  Sun  2000-09-03  Panthers   10    0    0    7  2000  Redskins    7    0    3   10  9/3/2000  1:01PM  Washington Redskins         NaN    Carolina Panthers
3           3  200009030atl     1  Sun  2000-09-03     49ers    7    7    7    7  2000   Falcons    6   16   14    0  9/3/2000  1:02PM      Atlanta Falcons         NaN  San Francisco 49ers
4           4  200009030pit     1  Sun  2000-09-03    Ravens   10    3    3    0  2000  Steelers    0    0    0    0  9/3/2000  1:02PM     Baltimore Ravens           @  Pittsburgh Steelers

### Visiting team scorelines only

In [5]:
games.columns

Index(['Unnamed: 0', 'GameID', 'Week', 'Day', 'DateStamp', 'Vteam', 'VQ1',
       'VQ2', 'VQ3', 'VQ4', 'Year', 'Hteam', 'HQ1', 'HQ2', 'HQ3', 'HQ4',
       'Date', 'Time', 'Winner/tie', 'Unnamed: 18', 'Loser/tie'],
      dtype='object')

In [47]:
games_Vscores = games.drop(['Unnamed: 0','Hteam', 'HQ1', 'HQ2', 'HQ3', 'HQ4',
       'Date','Winner/tie', 'Unnamed: 18', 'Loser/tie' ], axis=1)

In [48]:
games_Vscores.head()

         GameID  Week  Day   DateStamp     Vteam  VQ1  VQ2  VQ3  VQ4  Year    Time
0  200009030min     1  Sun  2000-09-03     Bears    7    6    7    7  2000  1:00PM
1  200009030kan     1  Sun  2000-09-03     Colts    0    7    7   13  2000  1:00PM
2  200009030was     1  Sun  2000-09-03  Panthers   10    0    0    7  2000  1:01PM
3  200009030atl     1  Sun  2000-09-03     49ers    7    7    7    7  2000  1:02PM
4  200009030pit     1  Sun  2000-09-03    Ravens   10    3    3    0  2000  1:02PM

In [9]:
games_Vscores.to_csv('data/NFL_games_Vscores.csv')

### Home team scorelines only

In [10]:
games.columns

Index(['Unnamed: 0', 'GameID', 'Week', 'Day', 'DateStamp', 'Vteam', 'VQ1',
       'VQ2', 'VQ3', 'VQ4', 'Year', 'Hteam', 'HQ1', 'HQ2', 'HQ3', 'HQ4',
       'Date', 'Time', 'Winner/tie', 'Unnamed: 18', 'Loser/tie'],
      dtype='object')

In [49]:
games_Hscores = games.drop(['Unnamed: 0','Vteam', 'VQ1', 'VQ2', 'VQ3', 'VQ4',
       'Date','Winner/tie', 'Unnamed: 18', 'Loser/tie' ], axis=1)

In [50]:
games_Hscores.head()

         GameID  Week  Day   DateStamp  Year     Hteam  HQ1  HQ2  HQ3  HQ4    Time
0  200009030min     1  Sun  2000-09-03  2000   Vikings    6    3    7   14  1:00PM
1  200009030kan     1  Sun  2000-09-03  2000    Chiefs    0    7    7    0  1:00PM
2  200009030was     1  Sun  2000-09-03  2000  Redskins    7    0    3   10  1:01PM
3  200009030atl     1  Sun  2000-09-03  2000   Falcons    6   16   14    0  1:02PM
4  200009030pit     1  Sun  2000-09-03  2000  Steelers    0    0    0    0  1:02PM

In [13]:
games_Hscores.to_csv('data/NFL_games_Hscores.csv')

### One Hot Encode Scores https://stackoverflow.com/questions/37292872/how-can-i-one-hot-encode-in-python

In [51]:
one_hot_V = pd.get_dummies(games_Vscores['Vteam'])

In [52]:
games_Vscores_enc = games_Vscores.drop(['Vteam'], axis=1)

In [53]:
games_Vscores_enc = games_Vscores_enc.join(one_hot_V)

In [54]:
games_Vscores_enc

                    GameID  Week  Day   DateStamp  VQ1  VQ2  VQ3  VQ4  Year    Time  49ers  Bears  Bengals  Bills  Broncos  Browns  Buccaneers  Cardinals  Chargers  Chiefs  Colts  Cowboys  Dolphins  Eagles  Falcons  Giants  Jaguars  Jets  Lions  Packers  Panthers  Patriots  Raiders  Rams  Ravens  Redskins  Saints  Seahawks  Steelers  Texans  Titans  Vikings
0             200009030min     1  Sun  2000-09-03    7    6    7    7  2000  1:00PM      0      1        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        0         0         0        0     0       0         0       0         0         0       0       0        0
1             200009030kan     1  Sun  2000-09-03    0    7    7   13  2000  1:00PM      0      0        0      0        0       0           0          0         0       0      1        0         0       0        0       0        0     0      0        0         0         0        0     0       0         0       0         0         0       0       0        0
2             200009030was     1  Sun  2000-09-03   10    0    0    7  2000  1:01PM      0      0        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        0         1         0        0     0       0         0       0         0         0       0       0        0
3             200009030atl     1  Sun  2000-09-03    7    7    7    7  2000  1:02PM      1      0        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        0         0         0        0     0       0         0       0         0         0       0       0        0
4             200009030pit     1  Sun  2000-09-03   10    3    3    0  2000  1:02PM      0      0        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        0         0         0        0     0       1         0       0         0         0       0       0        0
...                    ...   ...  ...         ...  ...  ...  ...  ...   ...     ...    ...    ...      ...    ...      ...     ...         ...        ...       ...     ...    ...      ...       ...     ...      ...     ...      ...   ...    ...      ...       ...       ...      ...   ...     ...       ...     ...       ...       ...     ...     ...      ...
5319  2019-DV-Vikings49ers   200  Sun  2020-01-12    7    3    0    0  2019  3:05PM      0      0        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        0         0         0        0     0       0         0       0         0         0       0       0        1
5320  2019-DV-TitansRavens   200  Sun  2020-01-12    7    7   14    0  2019  6:40PM      0      0        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        0         0         0        0     0       0         0       0         0         0       0       1        0
5321  2019-CC-TitansChiefs   300  Sun  2020-01-19   10    7    0    7  2019  3:05PM      0      0        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        0         0         0        0     0       0         0       0         0         0       0       1        0
5322  2019-CC-Packers49ers   300  Sun  2020-01-19    0    0    7   13  2019  6:40PM      0      0        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        1         0         0        0     0       0         0       0         0         0       0       0        0
5323   2019-SB-49ersChiefs   400  Sun  2020-02-02    3    7   10    0  2019  6:30PM      1      0        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        0         0         0        0     0       0         0       0         0         0       0       0        0

[5324 rows x 42 columns]

In [19]:
games_Vscores.to_csv('data/NFL_games_Vscores_teams_encoded.csv')

In [55]:
one_hot_H = pd.get_dummies(games_Hscores['Hteam'])

In [56]:
games_Hscores_enc = games_Hscores.drop(['Hteam'], axis=1)

In [57]:
games_Hscores_enc = games_Hscores_enc.join(one_hot_H)

In [58]:
games_Hscores_enc

                    GameID  Week  Day   DateStamp  Year  HQ1  HQ2  HQ3  HQ4    Time  49ers  Bears  Bengals  Bills  Broncos  Browns  Buccaneers  Cardinals  Chargers  Chiefs  Colts  Cowboys  Dolphins  Eagles  Falcons  Giants  Jaguars  Jets  Lions  Packers  Panthers  Patriots  Raiders  Rams  Ravens  Redskins  Saints  Seahawks  Steelers  Texans  Titans  Vikings
0             200009030min     1  Sun  2000-09-03  2000    6    3    7   14  1:00PM      0      0        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        0         0         0        0     0       0         0       0         0         0       0       0        1
1             200009030kan     1  Sun  2000-09-03  2000    0    7    7    0  1:00PM      0      0        0      0        0       0           0          0         0       1      0        0         0       0        0       0        0     0      0        0         0         0        0     0       0         0       0         0         0       0       0        0
2             200009030was     1  Sun  2000-09-03  2000    7    0    3   10  1:01PM      0      0        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        0         0         0        0     0       0         1       0         0         0       0       0        0
3             200009030atl     1  Sun  2000-09-03  2000    6   16   14    0  1:02PM      0      0        0      0        0       0           0          0         0       0      0        0         0       0        1       0        0     0      0        0         0         0        0     0       0         0       0         0         0       0       0        0
4             200009030pit     1  Sun  2000-09-03  2000    0    0    0    0  1:02PM      0      0        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        0         0         0        0     0       0         0       0         0         1       0       0        0
...                    ...   ...  ...         ...   ...  ...  ...  ...  ...     ...    ...    ...      ...    ...      ...     ...         ...        ...       ...     ...    ...      ...       ...     ...      ...     ...      ...   ...    ...      ...       ...       ...      ...   ...     ...       ...     ...       ...       ...     ...     ...      ...
5319  2019-DV-Vikings49ers   200  Sun  2020-01-12  2019    7    7   10    3  3:05PM      1      0        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        0         0         0        0     0       0         0       0         0         0       0       0        0
5320  2019-DV-TitansRavens   200  Sun  2020-01-12  2019    0    6    0    6  6:40PM      0      0        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        0         0         0        0     0       1         0       0         0         0       0       0        0
5321  2019-CC-TitansChiefs   300  Sun  2020-01-19  2019    7   14    0   14  3:05PM      0      0        0      0        0       0           0          0         0       1      0        0         0       0        0       0        0     0      0        0         0         0        0     0       0         0       0         0         0       0       0        0
5322  2019-CC-Packers49ers   300  Sun  2020-01-19  2019    7   20    7    3  6:40PM      1      0        0      0        0       0           0          0         0       0      0        0         0       0        0       0        0     0      0        0         0         0        0     0       0         0       0         0         0       0       0        0
5323   2019-SB-49ersChiefs   400  Sun  2020-02-02  2019    7    3    0   21  6:30PM      0      0        0      0        0       0           0          0         0       1      0        0         0       0        0       0        0     0      0        0         0         0        0     0       0         0       0         0         0       0       0        0

[5324 rows x 42 columns]

In [24]:
games_Hscores.to_csv('data/NFL_games_Hscores_teams_encoded.csv')